version: '3.8'
services:
  nacos:
    image: nacos/nacos-server:v3.1.0
    container_name: nacos
    environment:
      - MODE=standalone
      - NACOS_AUTH_ENABLE=false
      - NACOS_AUTH_TOKEN=SecretKey012345678901234567890123456789012345678901234567890123456789
      - NACOS_AUTH_IDENTITY_KEY=serverIdentity
      - NACOS_AUTH_IDENTITY_VALUE=security
    ports:
      - "8848:8848"
      - "9848:9848"
      - "8100:8080"
    networks:
      - coursehub-network
      
  catalog-db:
    image: mysql:8
    container_name: catalog-db-hw7
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: catalog_db
    ports:
      - "3307:3306"
    volumes:
      - catalog-db-data:/var/lib/mysql
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
    networks:
      - coursehub-network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 5s
      timeout: 5s
      retries: 5
    restart: unless-stopped

  enrollment-db:
    image: mysql:8
    container_name: enrollment-db-hw7
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: enrollment_db
    ports:
      - "3308:3306"
    volumes:
      - enrollment-db-data:/var/lib/mysql
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
    networks:
      - coursehub-network
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost" ]
      interval: 5s
      timeout: 5s
      retries: 5
    restart: unless-stopped

  user-db:
    image: mysql:8
    container_name: user-db-hw7
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: user_db
    ports:
      - "3309:3306"
    volumes:
      - user-db-data:/var/lib/mysql
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
    networks:
      - coursehub-network
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost" ]
      interval: 5s
      timeout: 5s
      retries: 5
    restart: unless-stopped
  
  catalog-service:
    build:
      context: ./catalog-service
      dockerfile: Dockerfile
#    container_name: catalog-service-hw7
    ports:
      - "8081:8081"
    environment:
      SPRING_PROFILES_ACTIVE: docker
      SPRING_DATASOURCE_URL: jdbc:mysql://catalog-db:3306/catalog_db?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: 123456
    depends_on:
      catalog-db:
        condition: service_healthy
      nacos:
        condition: service_started
    networks:
      - coursehub-network
    restart: unless-stopped

  user-service:
    build:
      context: ./user-service
      dockerfile: Dockerfile
#    container_name: user-service-hw7
    ports:
      - "8082:8082"
    environment:
      SPRING_PROFILES_ACTIVE: docker
      SPRING_DATASOURCE_URL: jdbc:mysql://user-db:3306/user_db?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: 123456
    depends_on:
      user-db:
        condition: service_healthy
      nacos:
        condition: service_started
    networks:
      - coursehub-network
    restart: unless-stopped


  enrollment-service:
    build:
      context: ./enrollment-service
      dockerfile: Dockerfile
#    container_name: enrollment-service-hw7
    ports:
      - "8083:8083"
    environment:
      SPRING_PROFILES_ACTIVE: docker
      SPRING_DATASOURCE_URL: jdbc:mysql://enrollment-db:3306/enrollment_db?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: 123456
    depends_on:
      enrollment-db:
        condition: service_healthy
      catalog-service:
        condition: service_started
      user-service:
        condition: service_started
      nacos:
        condition: service_started
    networks:
      - coursehub-network
    restart: unless-stopped

  
  

networks:
  coursehub-network:
    driver: bridge

volumes:
  catalog-db-data:
    driver: local
  enrollment-db-data:
    driver: local
  user-db-data:
    driver: local

